// Code generated by crd2pulumi DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package v1beta1

import (
	"context"
	"reflect"

	"errors"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/utilities"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// VMStaticScrapeList is a list of VMStaticScrape
type VMStaticScrapeList struct {
	pulumi.CustomResourceState

	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringOutput `pulumi:"apiVersion"`
	// List of vmstaticscrapes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items VMStaticScrapeTypeArrayOutput `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringOutput `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaOutput `pulumi:"metadata"`
}

// NewVMStaticScrapeList registers a new resource with the given unique name, arguments, and options.
func NewVMStaticScrapeList(ctx *pulumi.Context,
	name string, args *VMStaticScrapeListArgs, opts ...pulumi.ResourceOption) (*VMStaticScrapeList, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Items == nil {
		return nil, errors.New("invalid value for required argument 'Items'")
	}
	args.ApiVersion = pulumi.StringPtr("operator.victoriametrics.com/v1beta1")
	args.Kind = pulumi.StringPtr("VMStaticScrapeList")
	opts = utilities.PkgResourceDefaultOpts(opts)
	var resource VMStaticScrapeList
	err := ctx.RegisterResource("kubernetes:operator.victoriametrics.com/v1beta1:VMStaticScrapeList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVMStaticScrapeList gets an existing VMStaticScrapeList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVMStaticScrapeList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VMStaticScrapeListState, opts ...pulumi.ResourceOption) (*VMStaticScrapeList, error) {
	var resource VMStaticScrapeList
	err := ctx.ReadResource("kubernetes:operator.victoriametrics.com/v1beta1:VMStaticScrapeList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VMStaticScrapeList resources.
type vmstaticScrapeListState struct {
}

type VMStaticScrapeListState struct {
}

func (VMStaticScrapeListState) ElementType() reflect.Type {
	return reflect.TypeOf((*vmstaticScrapeListState)(nil)).Elem()
}

type vmstaticScrapeListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `pulumi:"apiVersion"`
	// List of vmstaticscrapes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items []VMStaticScrapeType `pulumi:"items"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `pulumi:"kind"`
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata *metav1.ListMeta `pulumi:"metadata"`
}

// The set of arguments for constructing a VMStaticScrapeList resource.
type VMStaticScrapeListArgs struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion pulumi.StringPtrInput
	// List of vmstaticscrapes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
	Items VMStaticScrapeTypeArrayInput
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind pulumi.StringPtrInput
	// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Metadata metav1.ListMetaPtrInput
}

func (VMStaticScrapeListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*vmstaticScrapeListArgs)(nil)).Elem()
}

type VMStaticScrapeListInput interface {
	pulumi.Input

	ToVMStaticScrapeListOutput() VMStaticScrapeListOutput
	ToVMStaticScrapeListOutputWithContext(ctx context.Context) VMStaticScrapeListOutput
}

func (*VMStaticScrapeList) ElementType() reflect.Type {
	return reflect.TypeOf((**VMStaticScrapeList)(nil)).Elem()
}

func (i *VMStaticScrapeList) ToVMStaticScrapeListOutput() VMStaticScrapeListOutput {
	return i.ToVMStaticScrapeListOutputWithContext(context.Background())
}

func (i *VMStaticScrapeList) ToVMStaticScrapeListOutputWithContext(ctx context.Context) VMStaticScrapeListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VMStaticScrapeListOutput)
}

// VMStaticScrapeListArrayInput is an input type that accepts VMStaticScrapeListArray and VMStaticScrapeListArrayOutput values.
// You can construct a concrete instance of `VMStaticScrapeListArrayInput` via:
//
//	VMStaticScrapeListArray{ VMStaticScrapeListArgs{...} }
type VMStaticScrapeListArrayInput interface {
	pulumi.Input

	ToVMStaticScrapeListArrayOutput() VMStaticScrapeListArrayOutput
	ToVMStaticScrapeListArrayOutputWithContext(context.Context) VMStaticScrapeListArrayOutput
}

type VMStaticScrapeListArray []VMStaticScrapeListInput

func (VMStaticScrapeListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VMStaticScrapeList)(nil)).Elem()
}

func (i VMStaticScrapeListArray) ToVMStaticScrapeListArrayOutput() VMStaticScrapeListArrayOutput {
	return i.ToVMStaticScrapeListArrayOutputWithContext(context.Background())
}

func (i VMStaticScrapeListArray) ToVMStaticScrapeListArrayOutputWithContext(ctx context.Context) VMStaticScrapeListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VMStaticScrapeListArrayOutput)
}

// VMStaticScrapeListMapInput is an input type that accepts VMStaticScrapeListMap and VMStaticScrapeListMapOutput values.
// You can construct a concrete instance of `VMStaticScrapeListMapInput` via:
//
//	VMStaticScrapeListMap{ "key": VMStaticScrapeListArgs{...} }
type VMStaticScrapeListMapInput interface {
	pulumi.Input

	ToVMStaticScrapeListMapOutput() VMStaticScrapeListMapOutput
	ToVMStaticScrapeListMapOutputWithContext(context.Context) VMStaticScrapeListMapOutput
}

type VMStaticScrapeListMap map[string]VMStaticScrapeListInput

func (VMStaticScrapeListMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VMStaticScrapeList)(nil)).Elem()
}

func (i VMStaticScrapeListMap) ToVMStaticScrapeListMapOutput() VMStaticScrapeListMapOutput {
	return i.ToVMStaticScrapeListMapOutputWithContext(context.Background())
}

func (i VMStaticScrapeListMap) ToVMStaticScrapeListMapOutputWithContext(ctx context.Context) VMStaticScrapeListMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VMStaticScrapeListMapOutput)
}

type VMStaticScrapeListOutput struct{ *pulumi.OutputState }

func (VMStaticScrapeListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**VMStaticScrapeList)(nil)).Elem()
}

func (o VMStaticScrapeListOutput) ToVMStaticScrapeListOutput() VMStaticScrapeListOutput {
	return o
}

func (o VMStaticScrapeListOutput) ToVMStaticScrapeListOutputWithContext(ctx context.Context) VMStaticScrapeListOutput {
	return o
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (o VMStaticScrapeListOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *VMStaticScrapeList) pulumi.StringOutput { return v.ApiVersion }).(pulumi.StringOutput)
}

// List of vmstaticscrapes. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
func (o VMStaticScrapeListOutput) Items() VMStaticScrapeTypeArrayOutput {
	return o.ApplyT(func(v *VMStaticScrapeList) VMStaticScrapeTypeArrayOutput { return v.Items }).(VMStaticScrapeTypeArrayOutput)
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o VMStaticScrapeListOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v *VMStaticScrapeList) pulumi.StringOutput { return v.Kind }).(pulumi.StringOutput)
}

// Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (o VMStaticScrapeListOutput) Metadata() metav1.ListMetaOutput {
	return o.ApplyT(func(v *VMStaticScrapeList) metav1.ListMetaOutput { return v.Metadata }).(metav1.ListMetaOutput)
}

type VMStaticScrapeListArrayOutput struct{ *pulumi.OutputState }

func (VMStaticScrapeListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*VMStaticScrapeList)(nil)).Elem()
}

func (o VMStaticScrapeListArrayOutput) ToVMStaticScrapeListArrayOutput() VMStaticScrapeListArrayOutput {
	return o
}

func (o VMStaticScrapeListArrayOutput) ToVMStaticScrapeListArrayOutputWithContext(ctx context.Context) VMStaticScrapeListArrayOutput {
	return o
}

func (o VMStaticScrapeListArrayOutput) Index(i pulumi.IntInput) VMStaticScrapeListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *VMStaticScrapeList {
		return vs[0].([]*VMStaticScrapeList)[vs[1].(int)]
	}).(VMStaticScrapeListOutput)
}

type VMStaticScrapeListMapOutput struct{ *pulumi.OutputState }

func (VMStaticScrapeListMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*VMStaticScrapeList)(nil)).Elem()
}

func (o VMStaticScrapeListMapOutput) ToVMStaticScrapeListMapOutput() VMStaticScrapeListMapOutput {
	return o
}

func (o VMStaticScrapeListMapOutput) ToVMStaticScrapeListMapOutputWithContext(ctx context.Context) VMStaticScrapeListMapOutput {
	return o
}

func (o VMStaticScrapeListMapOutput) MapIndex(k pulumi.StringInput) VMStaticScrapeListOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *VMStaticScrapeList {
		return vs[0].(map[string]*VMStaticScrapeList)[vs[1].(string)]
	}).(VMStaticScrapeListOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VMStaticScrapeListInput)(nil)).Elem(), &VMStaticScrapeList{})
	pulumi.RegisterInputType(reflect.TypeOf((*VMStaticScrapeListArrayInput)(nil)).Elem(), VMStaticScrapeListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VMStaticScrapeListMapInput)(nil)).Elem(), VMStaticScrapeListMap{})
	pulumi.RegisterOutputType(VMStaticScrapeListOutput{})
	pulumi.RegisterOutputType(VMStaticScrapeListArrayOutput{})
	pulumi.RegisterOutputType(VMStaticScrapeListMapOutput{})
}
